.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "RFC" "1" "October 2024" ""
.SH "NAME"
\fBrfc\fR \- Read RFCs in your terminal
.SH "SYNOPSIS"
\fBrfc\fR <command>|<number>
.SH "DESCRIPTION"
Show the RFC <number> in your terminal\. It uses a local cache to avoid re\-downloading each RFC every time\.
.SH "COMMANDS"
.TP
\fBsearch\fR <query>
Search for <query> in local RFCs using \fBgrep\fR\. Options are passed through\.
.TP
\fBlist\fR
List locally\-available RFCs\.
.TP
\fBsync\fR [week|month|all]
Batch download RFCs\. \fBweek\fR and \fBmonth\fR respectively download only RFCs that were added or updated during the last week/month\. \fBall\fR (default) downloads all RFCs\. It might take some time; be patient\.
.TP
\fBclear\fR
Clear the local cache\.
.SH "OPTIONS"
.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
Print the help and exit
.TP
\fB\-\-debug\fR
Enable the tracing of all Bash commands\. This must be the first argument\.
.SH "EXIT CODES"
0 Success\.
.P
1 RFC not found\.
.P
2 Unrecognized command\.
.P
3 Network error\.
.P
4 Neither \fBcurl\fR nor \fBwget\fR are installed\.
.SH "ENVIRONMENT"
.TP
\fBRFC_DIR\fR
Cache directory\. The default is \fB$XDG_CACHE_HOME/RFCs\fR if \fBXDG_CACHE_HOME\fR is defined, otherwise \fB~/\.cache/RFCs\fR\.
.TP
\fBPAGER\fR
Command to use to show RFCs\. The default is \fBless\fR\.
.TP
\fBCURL\fR
Command to use to download RFCs: \fBcurl\fR (default) or \fBwget\fR\.
.SH "EXAMPLES"
Read the RFC 2822:
.IP "" 4
.nf
$ rfc 2822
.fi
.IP "" 0
.SH "BUGS"
Bugs should be reported at \fIhttps://github\.com/bfontaine/rfc/issues\fR\.
.SH "AUTHOR"
Written by Baptiste Fontaine «b@ptistefontaine\.fr>>\.
