name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bc
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bc

      - name: Test Setup
        run: |
          bash -x ./test/before.sh

      - name: Tests
        run: |
          bash ./test/test.sh
